// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNQOzE7V1ITM9UGOgB3eOGlyung_Iq2s',
    appId: '1:1056794039802:web:c5d3f2d243046336918043',
    messagingSenderId: '1056794039802',
    projectId: 'gomla-bb127',
    authDomain: 'gomla-bb127.firebaseapp.com',
    storageBucket: 'gomla-bb127.firebasestorage.app',
    measurementId: 'G-KH20LZ0WKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNKKj5m6ouo0hHqbNMb83N_5UtR3ESGBY',
    appId: '1:1056794039802:android:34e54aab1311bd57918043',
    messagingSenderId: '1056794039802',
    projectId: 'gomla-bb127',
    storageBucket: 'gomla-bb127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQVZIIA9REDs6DeC0Gf0CG604fIc5Nkw',
    appId: '1:1056794039802:ios:cc81a98df28708c4918043',
    messagingSenderId: '1056794039802',
    projectId: 'gomla-bb127',
    storageBucket: 'gomla-bb127.firebasestorage.app',
    iosBundleId: 'com.gomla.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQVZIIA9REDs6DeC0Gf0CG604fIc5Nkw',
    appId: '1:1056794039802:ios:a4f6638a4c50ac0b918043',
    messagingSenderId: '1056794039802',
    projectId: 'gomla-bb127',
    storageBucket: 'gomla-bb127.firebasestorage.app',
    iosBundleId: 'no',
  );
}
